apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
    name: $(workload.metadata.name)$
    labels:
      app.kubernetes.io/part-of: $(workload.metadata.name)$
spec:
  interval: 1m
  url: $(workload.spec.source.git.url)$
  ref: $(workload.spec.source.git.ref)$