apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: knative-deployer
spec:
  template: 
    apiVersion: kappctrl.k14s.io/v1alpha1
    kind: App 
    metadata: 
        name: $(workload.metadata.name)$
    spec: 
      serviceAccountName: default
      fetch:
        - inline: 
            paths: 
              manifest.yml: |
                ---
                apiVersion: serving.knative.dev/v1
                kind: Service
                metadata:
                   name: $(workload.metadata.name)$
                spec: 
                  template:
                    metadata:
                      annotations:
                        autoscaling.knative.dev/minScale: "1"
                    spec:
                        serviceAccountName: default
                        containers:
                        - name: workload 
                          image: $(image)$
                          securityContext:
                            runAsUser: 1000
      template:
          - ytt: {}
      deploy:
          - kapp: {}

