---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: supply-chain-knative
spec:
  selector:
    apps.tanzu.vmware.com/workload-type: test-supply-chain
  resources:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: workload-git-repository

    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: workload-kpack-image
      sources:
        - resource: source-provider
          name: source

    - name: DeploymentCreator
      templateRef:
        kind: ClusterTemplate
        name: knative-deployer 
      images:
        - resource: image-builder 
          name: image